path: /home/jinlei/database/M3FD_Detection
vi: vi
ir: ir
labels: labels
train: meta/train.txt
val: meta/val.txt
test: meta/test.txt
data: /home/jinlei/database/M3FD_Detection
modality: rgb-ir
fusion: concat
imgsz: 224
batch: 4
epochs: 50
lr: 0.0001
num_workers: 2
seed: 7
nc: 6
names: [people, car, bus, motorcycle, lamp, truck]
